# Generated by Django 2.2 on 2020-01-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_feedback_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='moderate',
            field=models.BooleanField(default=False),
        ),
    ]
