# Generated by Django 2.2 on 2020-01-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_post_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'фото', 'verbose_name_plural': 'фотографии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'публикация', 'verbose_name_plural': 'новости'},
        ),
    ]
