# Generated by Django 2.2 on 2020-01-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('family_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
                ('e_type', models.CharField(choices=[('J', 'Прыжки'), ('M', 'Шаги'), ('S', 'Вращения')], max_length=1, verbose_name='тип')),
                ('repetitions', models.IntegerField(default=1, verbose_name='повторения')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
    ]
