# Generated by Django 2.2 on 2020-01-30 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0002_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='athlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlet_id', to='content_creator.Athlet', verbose_name='ребенок'),
        ),
        migrations.CreateModel(
            name='ExecutedElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_id', to='content_creator.Element', verbose_name='элемент')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_id', to='content_creator.Lesson', verbose_name='занятие')),
            ],
        ),
    ]
