# Generated by Django 2.2 on 2020-01-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0003_auto_20200130_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='executedelement',
            name='mark',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '4')], max_length=1),
        ),
    ]
