# Generated by Django 2.2 on 2020-01-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_creator', '0004_executedelement_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='repetitions',
        ),
        migrations.AddField(
            model_name='executedelement',
            name='repetitions',
            field=models.IntegerField(default=1, verbose_name='повторения'),
        ),
        migrations.AlterField(
            model_name='executedelement',
            name='mark',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
